Fixes issue with mkdirp in Windows
DeMoorJasper/parcel-plugin-imagemin pull request #21
Opened 2018-08-22 22:05 UTC by bre7

Not sure why there was a ENOENT error :S Parcel uses mkdirp as well.

2018-08-22 22:18 UTC, DeMoorJasper requested changes

2018-08-22 22:18 UTC, DeMoorJasper commented on lib/ImagePackager.js
>      await new Promise((resolve, reject) => {
Change this to use fs-extra as well, no need to wrap something that returns a promise in a promise :)

2018-08-22 22:55 UTC, bre7 commented
Done. Uses outputFile instead of ensureDir + writeFile (https://github.com/jprichardson/node-fs-extra/blob/master/docs/outputFile.md)

2018-08-22 22:59 UTC, DeMoorJasper commented
Didn't know about that fs-extra function, that's as clean as it gets

2018-08-22 22:59 UTC, DeMoorJasper approved these changes

2018-08-22 22:59 UTC, merged

2018-08-23 03:30 UTC, bre7 commented
Missing version bump in npm ?

2018-08-23 04:55 UTC, DeMoorJasper commented
Republished, should be updated now. Guess it was an npm bug or some network glitch